/**
 * ANRM 特色神经康复干预技术库。
 * 从 ANRM 肌骨神经康复系列手册提取,按神经通路标签化,待医师签字确认。
 */
import type { InterventionDef } from "./treatment.types";

export const INTERVENTIONS_CATALOG: readonly InterventionDef[] = [
  /* ============ 神经调控 ============ */
  {
    id: "neural-desensitization",
    category: "神经调控",
    name: "神经脱敏",
    neuroTargets: ["WDR神经元", "脑干"],
    indications: "C纤维/ASIC/TRPV敏化;神经性疼痛;痛觉过敏",
    parameters: "每点 20s,不超过 20s(防水肿);C7以上:胸锁乳突肌后1/2;T3以上:锁骨窝;欧伯氏点 C3-C5",
    pendingConfirmation: true,
  },
  {
    id: "gate-control",
    category: "神经调控",
    name: "闸门效应刺激(大纤维)",
    neuroTargets: ["IA纤维", "WDR神经元"],
    indications: "急性/慢性疼痛;WDR 兴奋状态",
    parameters: "TENS高频(80-100Hz)或低频(2-4Hz);按摩/压力;本体感觉输入关闭WDR",
    pendingConfirmation: true,
  },
  {
    id: "homologous-stim",
    category: "神经调控",
    name: "同源性刺激",
    neuroTargets: ["脊髓前角", "皮质"],
    indications: "对侧代偿;脊髓同源性康复;颈椎-腰椎同源利用",
    parameters: "刺激同侧上肢帮助下肢康复;动眼球/舌头激活脊髓前角;脑神经III-IV-VI-XII同源",
    pendingConfirmation: true,
  },
  {
    id: "cross-spinal",
    category: "神经调控",
    name: "跨脊髓反射",
    neuroTargets: ["IA纤维", "IB纤维"],
    indications: "对侧肢体制动;肌张力不平衡;拮抗肌过度紧张",
    parameters: "对侧同名肌等长收缩→释放同侧紧张;5-10s收缩→快速放松",
    pendingConfirmation: true,
  },
  {
    id: "baroreflex-tx",
    category: "神经调控",
    name: "压力感受反射调节",
    neuroTargets: ["自主神经"],
    indications: "交感神经过度兴奋;勃起功能障碍;脊髓损伤辅助评估",
    parameters: "颈动脉窦轻压;冰水30-60s(冷加压);Valsalva屏气",
    pendingConfirmation: true,
  },
  {
    id: "mirror-therapy",
    category: "神经调控",
    name: "镜像训练",
    neuroTargets: ["皮质"],
    indications: "偏瘫;CRPS;幻肢痛;运动想象障碍",
    parameters: "患侧隐藏→健侧镜像;双侧协调+节律;配合APA",
    pendingConfirmation: true,
  },
  {
    id: "motor-imagery-training",
    category: "神经调控",
    name: "运动想象训练",
    neuroTargets: ["皮质", "小脑"],
    indications: "卒中偏瘫早期;CRPS;运动学习障碍;术后运动恢复;慢性疼痛重塑",
    parameters: "三阶段:视觉想象(看)→动觉想象(感)→实际动作;每次 10-15min;清醒放松;可与镜像训练配合强化皮质激活",
    pendingConfirmation: true,
  },
  {
    id: "proprioception-training",
    category: "神经调控",
    name: "本体感觉专项训练",
    neuroTargets: ["IA纤维", "小脑", "皮质"],
    indications: "本体感觉减退;反复扭伤;关节位置觉异常",
    parameters: "闭眼定位;不同角度复位;振动刺激+主动匹配;9宫格/312区训练;2-3min/项",
    pendingConfirmation: true,
  },

  /* ============ 前庭-眼动训练 ============ */
  {
    id: "vor-training",
    category: "前庭-眼动训练",
    name: "前庭眼球反射(VOR)训练",
    neuroTargets: ["前庭", "脑干"],
    indications: "前庭功能减退;颈源性眩晕;脊柱不稳定",
    parameters: "凝视固定点→头转动;6秒有效窗口;30下/组;增益目标≈1.0",
    pendingConfirmation: true,
  },
  {
    id: "saccade-training",
    category: "前庭-眼动训练",
    name: "扫视训练(第8区)",
    neuroTargets: ["皮质", "前庭"],
    indications: "额叶功能障碍;扫视启动延迟;注意力缺陷",
    parameters: "双笔快速交替;10-15次/组;距离肩宽;启动<200ms",
    pendingConfirmation: true,
  },
  {
    id: "smooth-pursuit-training",
    category: "前庭-眼动训练",
    name: "平滑追踪训练",
    neuroTargets: ["小脑", "脑干"],
    indications: "眼球追踪不稳;小脑功能障碍;眩晕",
    parameters: "慢速追踪移动目标;左右/上下/8字;躯干追踪配合",
    pendingConfirmation: true,
  },
  {
    id: "convergence-training",
    category: "前庭-眼动训练",
    name: "视觉聚散度训练",
    neuroTargets: ["脑干"],
    indications: "聚散不足;近点远移;阅读困难",
    parameters: "成人10-15cm;儿童6-8cm;轻2min→中10min→重20min",
    pendingConfirmation: true,
  },
  {
    id: "red-green-training",
    category: "前庭-眼动训练",
    name: "红蓝/红绿眼镜训练",
    neuroTargets: ["皮质"],
    indications: "双眼抑制;立体视觉差;单侧视觉依赖",
    parameters: "红镜遮优势眼→迫弱眼工作;配合远近目标",
    pendingConfirmation: true,
  },

  /* ============ 原始反射整合 ============ */
  {
    id: "moro-integration",
    category: "原始反射整合",
    name: "惊吓反射(Moro)整合训练",
    neuroTargets: ["脑干"],
    indications: "Moro残留;焦虑;姿势控制障碍;ADHD;感觉过敏",
    parameters: "跨中线运动;慢速节奏性摇摆;前庭输入整合;包裹觉重训练",
    pendingConfirmation: true,
  },
  {
    id: "atnr-integration",
    category: "原始反射整合",
    name: "ATNR 整合训练",
    neuroTargets: ["皮质"],
    indications: "惯用手未建立;读写困难;左右分化差;坐姿扭曲",
    parameters: "转头侧爬行;交叉模式;节拍器配合40-54bpm",
    pendingConfirmation: true,
  },
  {
    id: "stnr-integration",
    category: "原始反射整合",
    name: "STNR 整合训练",
    neuroTargets: ["脑干", "皮质"],
    indications: "爬行困难;坐姿不良;专注力差;上下半身协调障碍",
    parameters: "四足位抬头/低头切换;头与手臂/腿部分离训练;猫式-牛式",
    pendingConfirmation: true,
  },
  {
    id: "tlr-integration",
    category: "原始反射整合",
    name: "TLR 整合训练",
    neuroTargets: ["前庭"],
    indications: "抬头/点头时姿势不稳;前庭未成熟;平衡感差",
    parameters: "前庭刺激+中线控制;不同头位平衡训练;翻滚训练",
    pendingConfirmation: true,
  },
  {
    id: "tectal-integration",
    category: "原始反射整合",
    name: "顶盖反射整合训练",
    neuroTargets: ["脑干", "皮质"],
    indications: "中脑顶盖未整合;头眼协调落后;姿势朝向反射异常;阅读追踪障碍",
    parameters: "缓慢头部运动配合视觉追随;前庭-视觉协调训练;中线对称活动;闭眼→睁眼渐进;每天10-15min",
    pendingConfirmation: true,
  },
  {
    id: "galant-integration",
    category: "原始反射整合",
    name: "脊髓背反射(Galant)整合训练",
    neuroTargets: ["皮质"],
    indications: "座位不安;注意力分散;排尿控制障碍;腰部敏感",
    parameters: "慢速背部刷擦脱敏;跨中线旋转;躯干扭转分离训练",
    pendingConfirmation: true,
  },
  {
    id: "palmar-grasp-integration",
    category: "原始反射整合",
    name: "抓握反射(Palmar)整合训练",
    neuroTargets: ["皮质"],
    indications: "精细动作差;书写困难;手部张力异常",
    parameters: "手掌脱敏→主动抓握-放松;不同材质触觉刺激;手部负重训练",
    pendingConfirmation: true,
  },
  {
    id: "plantar-grasp-integration",
    category: "原始反射整合",
    name: "足底抓握反射(Plantar)整合训练",
    neuroTargets: ["皮质"],
    indications: "扁平足;步态异常;足底敏感;站立不稳",
    parameters: "足底脱敏→主动跖屈-背屈;不同地面材质行走;赤足训练",
    pendingConfirmation: true,
  },
  {
    id: "sucking-rooting-integration",
    category: "原始反射整合",
    name: "吸吮/觅食反射整合训练",
    neuroTargets: ["脑干"],
    indications: "口腔运动障碍;构音不清;流涎;咀嚼困难",
    parameters: "口周脱敏;口唇闭合力训练;吸管/哨子/泡泡训练;舌位训练",
    pendingConfirmation: true,
  },
  {
    id: "landau-integration",
    category: "原始反射整合",
    name: "兰道反射(Landau)整合训练",
    neuroTargets: ["脑干", "皮质"],
    indications: "俯卧抬头困难;核心力量差;全身伸展不足",
    parameters: "俯卧→抬头→胸部离地→腿部伸展;超人式保持;逐渐延长",
    pendingConfirmation: true,
  },
  {
    id: "parachute-reflex-training",
    category: "原始反射整合",
    name: "降落伞反射训练",
    neuroTargets: ["皮质", "小脑"],
    indications: "保护性伸展反应缺失;摔倒风险高;前庭-视觉-本体整合差",
    parameters: "重心前移→诱发保护性伸手;不同方向推拉;软垫摔倒训练",
    pendingConfirmation: true,
  },

  /* ============ 运动康复 ============ */
  {
    id: "strength-concentric",
    category: "运动康复",
    name: "向心收缩肌力训练",
    neuroTargets: ["脊髓前角", "皮质"],
    indications: "肌力不足(MMT≤3-4);肌肉萎缩;术后力量恢复",
    parameters: "8-12RM×3组;向心阶段2s;每周3-5次;渐进超负荷原则",
    pendingConfirmation: true,
  },
  {
    id: "strength-eccentric",
    category: "运动康复",
    name: "离心收缩肌力训练",
    neuroTargets: ["IB纤维", "脊髓前角"],
    indications: "肌腱病变;肌肉拉伤恢复;离心力量不足;运动控制障碍",
    parameters: "离心阶段4-6s;负荷=1RM×70-85%;5-8次×3组;疼痛VAS可升至6",
    pendingConfirmation: true,
  },
  {
    id: "strength-isometric",
    category: "运动康复",
    name: "等长收缩训练",
    neuroTargets: ["脊髓前角"],
    indications: "急性期保护;关节疼痛期;术后早期;姿势稳定耐力不足",
    parameters: "保持5-10s;每组10-15次;多角度等长;疼痛期在无痛角度进行",
    pendingConfirmation: true,
  },
  {
    id: "strength-isokinetic",
    category: "运动康复",
    name: "等速肌力训练",
    neuroTargets: ["脊髓前角", "小脑"],
    indications: "运动专项康复;肌力精确评估与训练;运动员重返赛场",
    parameters: "角速度60°/s(力量)~180°/s(耐力);需等速设备;10次×3组",
    pendingConfirmation: true,
  },
  {
    id: "rom-passive",
    category: "运动康复",
    name: "被动关节活动度训练(PROM)",
    neuroTargets: ["IA纤维"],
    indications: "术后早期;昏迷/瘫痪;关节挛缩预防;疼痛限制主动活动",
    parameters: "缓慢稳定;全范围;每次10-15次;2-3次/天;如有骨化禁暴力",
    pendingConfirmation: true,
  },
  {
    id: "rom-active-assist",
    category: "运动康复",
    name: "助力主动关节活动度训练(AAROM)",
    neuroTargets: ["脊髓前角", "IA纤维"],
    indications: "肌力MMT 2-3级;主动ROM不足;术后中期",
    parameters: "助力在末端;客户主动完成可完成范围;10-15次×2-3组",
    pendingConfirmation: true,
  },
  {
    id: "rom-active",
    category: "运动康复",
    name: "主动关节活动度训练(AROM)",
    neuroTargets: ["脊髓前角", "皮质"],
    indications: "肌力MMT≥3级;关节僵硬;日常ROM维持",
    parameters: "无辅助全范围;缓慢控制;10-15次×2-3组;可配合镜子反馈",
    pendingConfirmation: true,
  },
  {
    id: "stability-core",
    category: "运动康复",
    name: "核心稳定性训练",
    neuroTargets: ["小脑", "前庭", "脊髓前角"],
    indications: "核心力量不足;腰痛;姿势异常;运动表现下降",
    parameters: "平板支撑→侧平板→死虫式→鸟狗式;渐进时长(20s→60s);每天2-3组",
    pendingConfirmation: true,
  },
  {
    id: "stability-joint",
    category: "运动康复",
    name: "关节稳定性训练",
    neuroTargets: ["IA纤维", "小脑"],
    indications: "韧带损伤后;关节松弛;反复扭伤;本体感觉减退",
    parameters: "闭链→半开链→开链渐进;不稳定平面;BOSU/平衡板;15-20次×3组",
    pendingConfirmation: true,
  },
  {
    id: "balance-static",
    category: "运动康复",
    name: "静态平衡训练",
    neuroTargets: ["前庭", "小脑", "IA纤维"],
    indications: "平衡功能障碍;跌倒风险;前庭康复基础阶段",
    parameters: "双足→单足→闭眼→软垫→干扰;30s-2min保持;每天2-3次",
    pendingConfirmation: true,
  },
  {
    id: "balance-dynamic",
    category: "运动康复",
    name: "动态平衡训练",
    neuroTargets: ["前庭", "小脑", "基底节"],
    indications: "步态不稳;转身困难;运动中平衡控制差",
    parameters: "行走中转头/转体;跨越障碍;急停急转;双任务平衡(边说边走)",
    pendingConfirmation: true,
  },
  {
    id: "coordination-training",
    category: "运动康复",
    name: "协调性训练",
    neuroTargets: ["小脑", "基底节"],
    indications: "共济失调;手足协调差;节律性运动障碍",
    parameters: "Frenkel体操;交替运动;双侧协调;节拍器配合;从简单到复杂",
    pendingConfirmation: true,
  },
  {
    id: "endurance-training",
    category: "运动康复",
    name: "耐力训练",
    neuroTargets: ["自主神经"],
    indications: "运动不耐受;心肺功能下降;疲劳;慢性疾病",
    parameters: "低负荷高重复(15-25次×3组);有氧40-60% HRR;逐步延长时间;每周3-5次",
    pendingConfirmation: true,
  },
  {
    id: "flexibility-stretch",
    category: "运动康复",
    name: "柔韧性/牵伸训练",
    neuroTargets: ["IB纤维", "IA纤维"],
    indications: "肌肉短缩;关节ROM受限;姿势不良;运动前准备",
    parameters: "静态牵伸保持15-30s×3-5次;动态牵伸预热10-15次;不引起锐痛",
    pendingConfirmation: true,
  },
  {
    id: "pnf-pattern",
    category: "运动康复",
    name: "PNF 螺旋对角线模式",
    neuroTargets: ["IA纤维", "IB纤维", "皮质"],
    indications: "偏瘫;运动模式异常;肌力不平衡;本体感觉促进",
    parameters: "D1屈/伸 D2屈/伸;节律性启动→慢反转→稳定性反转;言语指令+视觉引导",
    pendingConfirmation: true,
  },
  {
    id: "plyometric",
    category: "运动康复",
    name: "增强式/爆发力训练",
    neuroTargets: ["脊髓前角", "小脑"],
    indications: "运动恢复后期;爆发力不足;重返运动准备",
    parameters: "离心快速→向心爆发;8-12次×2-3组;充分休息(1:5工作休息比);充分热身后",
    pendingConfirmation: true,
  },
  {
    id: "functional-hiit",
    category: "运动康复",
    name: "功能性 HIIT 训练",
    neuroTargets: ["自主神经"],
    indications: "代谢功能改善;减重需求;心肺耐力提升",
    parameters: "Tabata 20s:10s×8轮;中等:40s:20s×5轮;运动:休息=1:1~1:3;确保动作质量",
    pendingConfirmation: true,
  },
  {
    id: "motor-control-isolate",
    category: "运动康复",
    name: "局部运动控制训练",
    neuroTargets: ["皮质", "小脑"],
    indications: "特定肌肉激活不足;代偿模式;错误运动模式",
    parameters: "低负荷高精度(如多裂肌激活10%MVC);超声/触诊反馈;从卧姿→坐姿→站姿渐进",
    pendingConfirmation: true,
  },

  /* ============ 手法/器械 ============ */
  {
    id: "quick-stretch",
    category: "手法/器械",
    name: "快速拉伸",
    neuroTargets: ["IB纤维"],
    indications: "肌张力增高;Golgi腱器抑制不足",
    parameters: "5次快速(1-2-3-4-5);拮抗对抗5-10s→快速拉伸;20%负荷离心",
    pendingConfirmation: true,
  },
  {
    id: "joint-mobilization",
    category: "手法/器械",
    name: "关节松动术",
    neuroTargets: ["IA纤维", "IB纤维"],
    indications: "关节僵硬;关节囊紧张;本体感觉减退",
    parameters: "快速5下/级;速度/角度影响肌腱和肌索",
    pendingConfirmation: true,
  },
  {
    id: "nerve-glide",
    category: "手法/器械",
    name: "神经松动术",
    neuroTargets: ["IA纤维"],
    indications: "神经卡压;神经滑动受限;Tinel阳性",
    parameters: "≤10次,次症状量(不诱发症状);缓慢滑动",
    pendingConfirmation: true,
  },
  {
    id: "e-stim",
    category: "手法/器械",
    name: "电刺激",
    neuroTargets: ["脊髓前角"],
    indications: "肌肉激活不足;神经肌肉接头传导障碍;臀肌激活",
    parameters: "NMES参数依肌肉而定;\"fire\"肌肉原则;频率20-50Hz",
    pendingConfirmation: true,
  },
  {
    id: "ultrasound-therapy",
    category: "手法/器械",
    name: "超声波治疗",
    neuroTargets: ["WDR神经元", "IB纤维"],
    indications: "肌腱病变(网球肘/跟腱炎);肌肉劳损;瘢痕组织松解;关节囊挛缩",
    parameters: "1MHz 深层(3-5cm),3MHz 浅表(<2cm);急性用脉冲式,慢性用连续式;强度 0.5-1.5 W/cm²;5-10min/区域",
    pendingConfirmation: true,
  },
  {
    id: "shock-wave-therapy",
    category: "手法/器械",
    name: "冲击波治疗",
    neuroTargets: ["WDR神经元", "皮质"],
    indications: "钙化性肌腱炎;足底筋膜炎;顽固网球肘;跟腱病;触发点松解",
    parameters: "焦点式 vs 径向式;能流密度 0.05-0.4 mJ/mm²;2000-3000脉冲/次;3-5次一疗程,间隔 1-2 周",
    pendingConfirmation: true,
  },
  {
    id: "lllt-laser-therapy",
    category: "手法/器械",
    name: "低强度激光治疗(LLLT)",
    neuroTargets: ["WDR神经元", "自主神经"],
    indications: "神经性疼痛;肌筋膜疼痛;伤口愈合;关节炎;腕管综合征",
    parameters: "波长 635-904nm;功率 50-500mW;能量密度 4-12 J/cm²;每点 30-60s;急性期用脉冲模式",
    pendingConfirmation: true,
  },

  /* ============ 运动控制/稳定性 ============ */
  {
    id: "scapular-stability",
    category: "运动控制/稳定性",
    name: "肩胛骨稳定训练",
    neuroTargets: ["小脑", "脊髓前角"],
    indications: "上斜方过度活跃;下斜方抑制;肩胛不稳",
    parameters: "1min/侧;上斜方拉长+下斜方激活;1根1根拉",
    pendingConfirmation: true,
  },
  {
    id: "apa-training",
    category: "运动控制/稳定性",
    name: "预期姿势调整(APA)",
    neuroTargets: ["基底节", "皮质"],
    indications: "起步困难;姿势不稳;帕金森",
    parameters: "站/坐位→并脚/分脚;目标物(针刺);重心转移",
    pendingConfirmation: true,
  },
  {
    id: "metronome-training",
    category: "运动控制/稳定性",
    name: "节拍器节律训练",
    neuroTargets: ["基底节", "小脑"],
    indications: "步态节律差;帕金森;运动节律障碍",
    parameters: "40→54-60bpm渐进;外部→内部节律;PNF节律性启动",
    pendingConfirmation: true,
  },
  {
    id: "breathing-training",
    category: "运动控制/稳定性",
    name: "呼吸训练/迷走神经激活",
    neuroTargets: ["自主神经"],
    indications: "交感兴奋;焦虑;心率变异性降低",
    parameters: "3s吸/6s呼×10-15组;漱喉/吹气球;腹式呼吸",
    pendingConfirmation: true,
  },
  {
    id: "cpg-training",
    category: "运动控制/稳定性",
    name: "中枢模式发生器(CPG)训练",
    neuroTargets: ["脊髓前角", "脑干"],
    indications: "步态异常;脊髓损伤后运动恢复",
    parameters: "仰卧交替屈膝→左肘右膝交叉;持续节律性",
    pendingConfirmation: true,
  },
  {
    id: "figure-8-training",
    category: "运动控制/稳定性",
    name: "多轴线8字运动训练",
    neuroTargets: ["小脑", "IA纤维"],
    indications: "本体感觉障碍;关节位置觉减退",
    parameters: "闭眼慢速;多轴向(大疤/小疤/平疤);正确率≥85%",
    pendingConfirmation: true,
  },
  {
    id: "cervical-deep-extensor-training",
    category: "运动控制/稳定性",
    name: "颈深伸肌训练",
    neuroTargets: ["脊髓前角", "皮质"],
    indications: "慢性颈痛;颈源性头痛;颈椎不稳;上交叉综合征(头前伸位);挥鞭伤后",
    parameters: "俯卧点头(下颈段 C3-C7);四足位颈椎节段活动;等长收缩 10s×10;避免浅层(上斜方/肩胛提肌)代偿;每天 10-15min",
    pendingConfirmation: true,
  },
  {
    id: "cervical-deep-flexor-training",
    category: "运动控制/稳定性",
    name: "颈深屈肌训练",
    neuroTargets: ["脊髓前角", "皮质"],
    indications: "慢性颈痛;颈源性头痛;颈椎前馈稳定不足;挥鞭伤后;上交叉综合征",
    parameters: "仰卧点头(下颈段屈曲、后脑不离床);Stabilizer 压力生物反馈 22→30mmHg 渐进;10次×2-3组;胸锁乳突肌不应主导",
    pendingConfirmation: true,
  },
  {
    id: "gluteal-training",
    category: "运动控制/稳定性",
    name: "臀肌训练",
    neuroTargets: ["皮质", "脊髓前角"],
    indications: "臀失忆(Gluteal Amnesia);Trendelenburg 步态;单腿稳定不足;慢性腰痛;膝内翻(髌股疼痛)",
    parameters: "侧卧蚌式开合;俯卧/侧卧髋外旋;单腿臀桥;单腿RDL;侧向行走(monster walk);先等长激活再向心/离心",
    pendingConfirmation: true,
  },

  /* ============ 生活方式/代谢 ============ */
  {
    id: "dietary-intervention",
    category: "生活方式/代谢",
    name: "饮食/营养干预",
    neuroTargets: ["自主神经"],
    indications: "慢性炎症;脑肠轴失调;代谢综合征",
    parameters: "戒糖/多蔬菜/减少精碳;排除奶蛋麦(肠道菌群);维D 8000-12000IU;EPA+DHA 1000mg;维B12 1000mg",
    pendingConfirmation: true,
  },
  {
    id: "blood-sugar-control",
    category: "生活方式/代谢",
    name: "血糖管理",
    neuroTargets: ["自主神经"],
    indications: "血糖波动;胰岛素抵抗;慢性疼痛加重",
    parameters: "持续血糖监测;低GI饮食;定时进食",
    pendingConfirmation: true,
  },
  {
    id: "sleep-hygiene",
    category: "生活方式/代谢",
    name: "睡眠卫生指导",
    neuroTargets: ["自主神经"],
    indications: "睡眠障碍;昼夜节律紊乱;慢性疼痛",
    parameters: "固定作息;睡前屏幕限制;环境优化;呼吸放松",
    pendingConfirmation: true,
  },
  {
    id: "aerobic-training",
    category: "生活方式/代谢",
    name: "有氧训练",
    neuroTargets: ["自主神经"],
    indications: "线粒体功能下降;肺活量↓;ATP不足",
    parameters: "肺活量→线粒体→ATP;中等强度;每天30min",
    pendingConfirmation: true,
  },
];
