/**
 * 8 个预设积分规则 — 首次加载时注入,builtin=true(可改不可删)
 */
import type { PointsRule, TierConfig } from "./models";

export const BUILTIN_RULES: PointsRule[] = [
  {
    id: "builtin_encounter_closed_award",
    name: "完成就诊奖",
    enabled: true,
    builtin: true,
    trigger: "encounter.closed",
    conditions: [],
    action: { kind: "award_fixed", points: 50, reason: "完成就诊奖励" },
    cooldownDays: 0,
    maxPerPatient: 0,
    priority: 10,
    order: 1,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_encounter_amount_ratio",
    name: "消费积分(就诊)",
    enabled: true,
    builtin: true,
    trigger: "encounter.closed",
    conditions: [],
    action: { kind: "award_ratio", pointsPerYuan: 1, reason: "消费积分(就诊,1元=1积分)" },
    cooldownDays: 0,
    maxPerPatient: 0,
    priority: 5,
    order: 2,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_billing_consumed_ratio",
    name: "消费积分(扣款)",
    enabled: true,
    builtin: true,
    trigger: "billing.consumed",
    conditions: [],
    action: { kind: "award_ratio", pointsPerYuan: 1, reason: "消费积分(扣款,1元=1积分)" },
    cooldownDays: 0,
    maxPerPatient: 0,
    priority: 5,
    order: 9,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_billing_recharged_bonus",
    name: "充值奖励",
    enabled: true,
    builtin: true,
    trigger: "billing.recharged",
    conditions: [],
    action: { kind: "award_fixed", points: 50, reason: "充值奖励" },
    cooldownDays: 1,
    maxPerPatient: 0,
    priority: 10,
    order: 10,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_diagnosis_award",
    name: "完成诊断",
    enabled: true,
    builtin: true,
    trigger: "diagnosis.created",
    conditions: [],
    action: { kind: "award_fixed", points: 30, reason: "完成诊断" },
    cooldownDays: 0,
    maxPerPatient: 0,
    priority: 10,
    order: 3,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_patient_registered",
    name: "注册即赠",
    enabled: true,
    builtin: true,
    trigger: "patient.created",
    conditions: [],
    action: { kind: "award_fixed", points: 10, reason: "新会员注册" },
    cooldownDays: 0,
    maxPerPatient: 1,
    priority: 10,
    order: 4,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_share_sent",
    name: "分享随访",
    enabled: true,
    builtin: true,
    trigger: "share.sent",
    conditions: [],
    action: { kind: "award_fixed", points: 20, reason: "分享随访方案" },
    cooldownDays: 7,
    maxPerPatient: 0,
    priority: 10,
    order: 5,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_encounter_5th_milestone",
    name: "复诊里程碑",
    enabled: true,
    builtin: true,
    trigger: "encounter.nth",
    conditions: [],
    action: { kind: "award_fixed", points: 200, reason: "第 5 次就诊里程碑" },
    cooldownDays: 0,
    maxPerPatient: 1,
    priority: 20,
    order: 6,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_patient_recommend",
    name: "推荐奖励",
    enabled: true,
    builtin: true,
    trigger: "patient.recommend",
    conditions: [],
    action: { kind: "award_fixed", points: 100, reason: "推荐新患者" },
    cooldownDays: 0,
    maxPerPatient: 0,
    priority: 10,
    order: 7,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_birthday_gift",
    name: "生日礼包",
    enabled: true,
    builtin: true,
    trigger: "patient.birthday",
    conditions: [],
    action: { kind: "award_fixed", points: 200, reason: "生日礼包" },
    cooldownDays: 365,
    maxPerPatient: 1,
    priority: 10,
    order: 8,
    validFrom: null,
    validUntil: null,
  },
];

export const DEFAULT_TIERS: TierConfig[] = [
  { tier: "regular", name: "普通会员", color: "#9CA3AF", icon: "👤", minTotalSpent: 0, pointMultiplier: 1, discountOnRedeem: 1 },
  { tier: "silver", name: "银卡", color: "#C0C0C0", icon: "🥈", minTotalSpent: 2000, pointMultiplier: 1.2, discountOnRedeem: 0.95 },
  { tier: "gold", name: "金卡", color: "#FFD700", icon: "🥇", minTotalSpent: 8000, pointMultiplier: 1.5, discountOnRedeem: 0.9 },
  { tier: "diamond", name: "钻石", color: "#B9F2FF", icon: "💎", minTotalSpent: 20000, pointMultiplier: 2, discountOnRedeem: 0.8 },
];