/**
 * 8 个预设积分规则 — 首次加载时注入,builtin=true(可改不可删)
 */
import type { PointsRule, TierConfig, RewardProduct } from "./models";

export const BUILTIN_RULES: PointsRule[] = [
  {
    id: "builtin_encounter_closed_award",
    name: "完成就诊奖",
    enabled: true,
    builtin: true,
    trigger: "encounter.closed",
    conditions: [],
    action: { kind: "award_fixed", points: 50, reason: "完成就诊奖励" },
    cooldownDays: 0,
    maxPerPatient: 0,
    priority: 10,
    order: 1,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_encounter_amount_ratio",
    name: "消费积分(就诊)",
    enabled: false,
    builtin: true,
    trigger: "encounter.closed",
    conditions: [],
    action: { kind: "award_ratio", pointsPerYuan: 1, reason: "消费积分(就诊,1元=1积分)" },
    cooldownDays: 0,
    maxPerPatient: 0,
    priority: 5,
    order: 2,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_billing_consumed_ratio",
    name: "消费积分(扣款)",
    enabled: true,
    builtin: true,
    trigger: "billing.consumed",
    conditions: [],
    action: { kind: "award_ratio", pointsPerYuan: 1, reason: "消费积分(扣款,1元=1积分)" },
    cooldownDays: 0,
    maxPerPatient: 0,
    priority: 5,
    order: 9,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_billing_recharged_bonus",
    name: "充值奖励",
    enabled: true,
    builtin: true,
    trigger: "billing.recharged",
    conditions: [],
    action: { kind: "award_fixed", points: 50, reason: "充值奖励" },
    cooldownDays: 1,
    maxPerPatient: 0,
    priority: 10,
    order: 10,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_diagnosis_award",
    name: "完成诊断",
    enabled: true,
    builtin: true,
    trigger: "diagnosis.created",
    conditions: [],
    action: { kind: "award_fixed", points: 30, reason: "完成诊断" },
    cooldownDays: 0,
    maxPerPatient: 0,
    priority: 10,
    order: 3,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_patient_registered",
    name: "注册即赠",
    enabled: true,
    builtin: true,
    trigger: "patient.created",
    conditions: [],
    action: { kind: "award_fixed", points: 10, reason: "新会员注册" },
    cooldownDays: 0,
    maxPerPatient: 1,
    priority: 10,
    order: 4,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_share_sent",
    name: "分享随访",
    enabled: true,
    builtin: true,
    trigger: "share.sent",
    conditions: [],
    action: { kind: "award_fixed", points: 20, reason: "分享随访方案" },
    cooldownDays: 7,
    maxPerPatient: 0,
    priority: 10,
    order: 5,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_encounter_5th_milestone",
    name: "复诊里程碑",
    enabled: true,
    builtin: true,
    trigger: "encounter.nth",
    conditions: [],
    action: { kind: "award_fixed", points: 200, reason: "第 5 次就诊里程碑" },
    cooldownDays: 0,
    maxPerPatient: 1,
    priority: 20,
    order: 6,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_patient_recommend",
    name: "推荐奖励",
    enabled: true,
    builtin: true,
    trigger: "patient.recommend",
    conditions: [],
    action: { kind: "award_fixed", points: 100, reason: "推荐新客户" },
    cooldownDays: 0,
    maxPerPatient: 0,
    priority: 10,
    order: 7,
    validFrom: null,
    validUntil: null,
  },
  {
    id: "builtin_birthday_gift",
    name: "生日礼包",
    enabled: true,
    builtin: true,
    trigger: "patient.birthday",
    conditions: [],
    action: { kind: "award_fixed", points: 200, reason: "生日礼包" },
    cooldownDays: 365,
    maxPerPatient: 1,
    priority: 10,
    order: 8,
    validFrom: null,
    validUntil: null,
  },
];

export const DEFAULT_TIERS: TierConfig[] = [
  { tier: "regular", name: "普通会员", color: "#9CA3AF", icon: "👤", minTotalSpent: 0, pointMultiplier: 1, discountOnRedeem: 1 },
  { tier: "silver", name: "银卡", color: "#C0C0C0", icon: "🥈", minTotalSpent: 2000, pointMultiplier: 1.2, discountOnRedeem: 1 },
  { tier: "gold", name: "金卡", color: "#FFD700", icon: "🥇", minTotalSpent: 8000, pointMultiplier: 1.5, discountOnRedeem: 1 },
  { tier: "diamond", name: "钻石", color: "#B9F2FF", icon: "💎", minTotalSpent: 20000, pointMultiplier: 2, discountOnRedeem: 1 },
];

export const REWARD_SEED: RewardProduct[] = [
  { id: "reward_elastics", name: "弹力带训练包", description: "含 5 条不同阻力的弹力带 + 训练手册", category: "training", pointsCost: 300, imageEmoji: "🩰", stock: -1, tierRequired: null, enabled: true, createdAt: new Date().toISOString() },
  { id: "reward_balance_disc", name: "平衡训练光盘", description: "12 节平衡训练高清视频", category: "training", pointsCost: 500, imageEmoji: "💿", stock: -1, tierRequired: null, enabled: true, createdAt: new Date().toISOString() },
  { id: "reward_phone_followup", name: "电话回访 1 次", description: "治疗师主动电话回访 30 分钟", category: "service", pointsCost: 800, imageEmoji: "📞", stock: -1, tierRequired: "silver", enabled: true, createdAt: new Date().toISOString() },
  { id: "reward_online_qa", name: "在线答疑 30 分钟", description: "治疗师在线视频答疑", category: "consult", pointsCost: 1000, imageEmoji: "💬", stock: -1, tierRequired: "silver", enabled: true, createdAt: new Date().toISOString() },
  { id: "reward_discount_90", name: "9 折就诊券", description: "下次就诊 9 折优惠", category: "discount", pointsCost: 500, imageEmoji: "🎟️", stock: -1, tierRequired: null, enabled: true, createdAt: new Date().toISOString() },
  { id: "reward_free_visit", name: "免费复诊券", description: "下次复诊免费一次", category: "service", pointsCost: 2000, imageEmoji: "🎫", stock: -1, tierRequired: "gold", enabled: true, createdAt: new Date().toISOString() },
  { id: "reward_expert", name: "三甲专家会诊咨询", description: "三甲康复专家 30 分钟会诊咨询", category: "consult", pointsCost: 5000, imageEmoji: "👨‍⚕️", stock: 5, tierRequired: "diamond", enabled: true, createdAt: new Date().toISOString() },
  { id: "reward_plan", name: "个性化训练计划定制", description: "治疗师 1 对 1 定制 4 周训练计划", category: "training", pointsCost: 2000, imageEmoji: "📋", stock: -1, tierRequired: "silver", enabled: true, createdAt: new Date().toISOString() },
];