/**
 * ANRM 特色临床神经科学查体目录。
 * 从 ANRM 肌骨神经康复系列手册提取,正常值/分级待医师签字确认。
 */
import type { ExamItemDef } from "./exam.types";

export const EXAM_CATALOG: readonly ExamItemDef[] = [
  /* ============ 原始反射 ============ */
  {
    id: "moro",
    category: "原始反射",
    name: "惊吓反射(Moro)",
    dataType: "pos-neg",
    side: "single",
    normalRef: "阴性(3月后应消失)",
    abnormalMeaning: "阳性提示中脑/脑干未整合,常见于 ADHD、焦虑、姿势控制障碍",
  },
  {
    id: "spinal-galant",
    category: "原始反射",
    name: "脊髓背反射(Galant)",
    dataType: "pos-neg",
    side: "both",
    normalRef: "阴性(9月后应消失)",
    abnormalMeaning: "阳性提示 T12-L1 水平神经兴奋性增高,与排尿控制相关",
  },
  {
    id: "tlr",
    category: "原始反射",
    name: "迷路反射(TLR)",
    dataType: "select",
    side: "single",
    options: ["阴性", "轻度阳性", "中度阳性", "重度阳性"],
    normalRef: "阴性(3岁后)",
    abnormalMeaning: "抬头/点头时躯干晃动,前庭系统未成熟",
  },
  {
    id: "atnr",
    category: "原始反射",
    name: "不对称性颈反射(ATNR)",
    dataType: "select",
    side: "both",
    options: ["阴性", "弱阳性", "强阳性"],
    normalRef: "阴性(6月后应消失)",
    abnormalMeaning: "残留影响惯用手发育、读写能力、左右分化",
  },
  {
    id: "stnr",
    category: "原始反射",
    name: "对称性颈反射(STNR)",
    dataType: "pos-neg",
    side: "single",
    normalRef: "阴性(11月后应消失)",
    abnormalMeaning: "残留影响爬行、坐姿、专注力",
  },
  {
    id: "palmar-grasp",
    category: "原始反射",
    name: "抓握反射",
    dataType: "pos-neg",
    side: "both",
    normalRef: "阴性(3-4 月后应消失,转为有意识抓握)",
    abnormalMeaning: "阳性提示大脑皮质抑制不足,影响手部精细动作与学习;持续存在 > 6 月需评估脑损伤",
  },
  {
    id: "tectal-reflex",
    category: "原始反射",
    name: "顶盖反射",
    dataType: "pos-neg",
    side: "single",
    normalRef: "阴性(具体消退月龄待医师确认)",
    abnormalMeaning: "阳性提示中脑顶盖/脑干未整合,常合并姿势控制与协调障碍",
  },
  {
    id: "head-righting-pull-sit",
    category: "原始反射",
    name: "拉坐头竖立反射",
    dataType: "select",
    side: "single",
    options: ["阴性", "弱阳性(头略滞后)", "强阳性(头严重滞后)"],
    normalRef: "阴性(2-3 月后应消失,转为有意识头控)",
    abnormalMeaning: "弱阳性提示颈立直反射未整合,影响头控、坐位稳定;强阳性需排查中枢运动发育迟缓",
  },
  {
    id: "babinski-primitive",
    category: "原始反射",
    name: "巴宾斯基反射",
    dataType: "pos-neg",
    side: "both",
    normalRef: "阴性(12-24 月后应消失;之后阳性视为异常)",
    abnormalMeaning: "预期月龄后仍阳性提示皮质脊髓束未髓鞘化或上位运动神经元损伤",
  },

  /* ============ 神经反射和病理反射 ============ */
  {
    id: "babinski",
    category: "神经反射和病理反射",
    name: "巴宾斯基征",
    dataType: "select",
    side: "both",
    options: ["阴性", "弱阳性", "强阳性"],
    normalRef: "阴性(成人)",
    abnormalMeaning: "阳性提示锥体束损伤;左阳→右脑,右阳→左脑",
  },
  {
    id: "hoffmann",
    category: "神经反射和病理反射",
    name: "霍夫曼征",
    dataType: "pos-neg",
    side: "both",
    normalRef: "阴性",
    abnormalMeaning: "阳性提示上运动神经元病变(颈髓以上)",
  },
  {
    id: "oppenheim",
    category: "神经反射和病理反射",
    name: "奥本海姆征",
    dataType: "pos-neg",
    side: "both",
    normalRef: "阴性",
    abnormalMeaning: "阳性提示锥体束损伤",
  },
  {
    id: "gordon",
    category: "神经反射和病理反射",
    name: "戈登征",
    dataType: "pos-neg",
    side: "both",
    normalRef: "阴性",
    abnormalMeaning: "阳性提示锥体束损伤",
  },
  {
    id: "chaddock",
    category: "神经反射和病理反射",
    name: "查多克征",
    dataType: "pos-neg",
    side: "both",
    normalRef: "阴性",
    abnormalMeaning: "阳性提示锥体束损伤",
  },
  {
    id: "clonus",
    category: "神经反射和病理反射",
    name: "踝阵挛",
    dataType: "pos-neg",
    side: "both",
    normalRef: "阴性",
    abnormalMeaning: "阳性提示上运动神经元病变(脊髓腰膨大以上)",
  },
  {
    id: "knee-clonus",
    category: "神经反射和病理反射",
    name: "髌阵挛",
    dataType: "pos-neg",
    side: "both",
    normalRef: "阴性",
    abnormalMeaning: "阳性提示上运动神经元病变",
  },
  {
    id: "pupillary-reflex",
    category: "神经反射和病理反射",
    name: "瞳孔对光反射",
    dataType: "select",
    side: "both",
    options: ["灵敏", "迟钝", "消失"],
    normalRef: "灵敏(幅度/速度/频率正常)",
    abnormalMeaning: "迟钝/消失提示动眼神经(III)或中脑病变",
  },

  /* ============ 前庭-眼动(ANRM 特色) ============ */
  {
    id: "vor-head-impulse",
    category: "前庭-眼动",
    name: "甩头试验(Head Impulse)",
    dataType: "pos-neg",
    side: "both",
    normalRef: "阴性(眼动可代偿)",
    abnormalMeaning: "阳性提示前庭眼反射(VOR)通路异常",
  },
  {
    id: "vor-gain",
    category: "前庭-眼动",
    name: "VOR 增益",
    dataType: "number",
    side: "both",
    unit: "倍",
    normalRef: "≈1.0",
    abnormalMeaning: "<0.8 前庭功能减退;>1.2 小脑代偿过度",
  },
  {
    id: "saccade",
    category: "前庭-眼动",
    name: "扫视(Saccade)-第8区",
    dataType: "select",
    side: "single",
    options: ["正常", "启动延迟", "欠冲", "过冲"],
    normalRef: "快速准确,启动<200ms",
    abnormalMeaning: "延迟提示额叶/第8区问题",
  },
  {
    id: "smooth-pursuit",
    category: "前庭-眼动",
    name: "平滑追踪(Smooth Pursuit)",
    dataType: "select",
    side: "both",
    options: ["正常", "扫视性追踪", "显著受限"],
    normalRef: "眼球可平滑追踪移动目标",
    abnormalMeaning: "扫视性追踪提示脑干/小脑/顶叶病变",
  },
  {
    id: "vergence",
    category: "前庭-眼动",
    name: "视轴聚散度(Convergence)",
    dataType: "number",
    side: "single",
    unit: "cm",
    normalRef: "成人10-15cm,儿童6-8cm",
    abnormalMeaning: ">15cm 聚散不足,中脑/动眼神经核问题",
  },
  {
    id: "okn",
    category: "前庭-眼动",
    name: "视动眼反射(OKN)",
    dataType: "select",
    side: "both",
    options: ["对称正常", "左弱", "右弱", "消失"],
    normalRef: "双向诱发出对称眼震,慢相跟踪视动条纹、快相回跳",
    abnormalMeaning: "单侧减弱→同侧颞叶/脑干/小脑病变;消失→广泛脑干功能障碍",
  },

  /* ============ 反射 / 肌张力 ============ */
  {
    id: "deep-reflex-biceps",
    category: "反射",
    name: "肱二头肌反射",
    dataType: "grade-0-4",
    side: "both",
    normalRef: "2+",
    abnormalMeaning: "0-1+ 下运动神经元;3-4+ 上运动神经元",
  },
  {
    id: "deep-reflex-triceps",
    category: "反射",
    name: "肱三头肌反射",
    dataType: "grade-0-4",
    side: "both",
    normalRef: "2+",
  },
  {
    id: "deep-reflex-brachioradialis",
    category: "反射",
    name: "桡骨膜反射",
    dataType: "grade-0-4",
    side: "both",
    normalRef: "2+",
  },
  {
    id: "deep-reflex-patellar",
    category: "反射",
    name: "膝腱反射",
    dataType: "grade-0-4",
    side: "both",
    normalRef: "2+",
  },
  {
    id: "deep-reflex-achilles",
    category: "反射",
    name: "跟腱反射",
    dataType: "grade-0-4",
    side: "both",
    normalRef: "2+",
    abnormalMeaning: "消失提示S1-S2神经根病变",
  },
  {
    id: "mas",
    category: "反射",
    name: "改良 Ashworth 痉挛量表(MAS)",
    dataType: "select",
    side: "both",
    options: ["0", "1", "1+", "2", "3", "4"],
    normalRef: "0",
    abnormalMeaning: "≥1 痉挛,分级越高痉挛越重",
  },

  /* ============ 感觉 / 本体感觉 ============ */
  {
    id: "tactile",
    category: "感觉",
    name: "浅感觉(触觉)",
    dataType: "select",
    side: "both",
    options: ["正常", "减退", "消失", "过敏"],
    normalRef: "正常",
  },
  {
    id: "pain-sense",
    category: "感觉",
    name: "痛觉",
    dataType: "select",
    side: "both",
    options: ["正常", "减退", "消失", "过敏"],
    normalRef: "正常",
  },
  {
    id: "temperature-sense",
    category: "感觉",
    name: "温度觉",
    dataType: "select",
    side: "both",
    options: ["正常", "减退", "消失"],
    normalRef: "正常",
  },
  {
    id: "vibration-sense",
    category: "感觉",
    name: "震动觉",
    dataType: "select",
    side: "both",
    options: ["正常", "减退", "消失"],
    normalRef: "正常",
    abnormalMeaning: "减退提示脊髓后索病变",
  },
  {
    id: "joint-position",
    category: "感觉",
    name: "关节位置觉",
    dataType: "select",
    side: "both",
    options: ["正常", "减退", "消失"],
    normalRef: "正常",
    abnormalMeaning: "减退提示脊髓后索/薄束楔束病变,比疼痛觉更重要(ANRM)",
  },
  {
    id: "two-point",
    category: "感觉",
    name: "两点辨识觉",
    dataType: "number",
    side: "both",
    unit: "mm",
    normalRef: "指尖2-4mm,手掌8-10mm,背部40-70mm",
    abnormalMeaning: "增大提示感觉通路/皮层感觉区病变",
  },
  /* 指压试验(末梢循环)已移到"自律神经"类下 */

  /* ============ 小脑 ============ */
  {
    id: "finger-nose",
    category: "小脑与平衡",
    name: "指鼻试验",
    dataType: "select",
    side: "both",
    options: ["正常", "轻度不稳", "明显不稳", "无法完成"],
    normalRef: "正常",
    abnormalMeaning: "意向性震颤→小脑病变",
  },
  {
    id: "heel-shin",
    category: "小脑与平衡",
    name: "跟膝胫试验",
    dataType: "select",
    side: "both",
    options: ["正常", "轻度不稳", "明显不稳", "无法完成"],
    normalRef: "正常",
  },
  {
    id: "diadochokinesia",
    category: "小脑与平衡",
    name: "轮替动作",
    dataType: "select",
    side: "both",
    options: ["正常", "笨拙", "不能完成"],
    normalRef: "正常",
    abnormalMeaning: "轮替运动障碍→小脑半球病变",
  },
  {
    id: "rebound-test",
    category: "小脑与平衡",
    name: "反跳试验(Stewart-Holmes)",
    dataType: "select",
    side: "both",
    options: ["正常", "阳性(不能制动)"],
    normalRef: "正常(被检肢体能立即制动)",
    abnormalMeaning: "阳性提示小脑病灶,同侧肢体不能制动",
  },
  {
    id: "tandem-gait",
    category: "小脑与平衡",
    name: "串联步态(Tandem Gait)",
    dataType: "select",
    side: "single",
    options: ["正常", "不稳", "不能完成"],
    normalRef: "直线行走足跟接足趾无偏移",
    abnormalMeaning: "不稳/不能完成→小脑或深感觉病变",
  },
  {
    id: "romberg",
    category: "小脑与平衡",
    name: "闭目难立(Romberg)",
    dataType: "select",
    side: "single",
    options: ["阴性", "阳性(闭眼后摇摆/跌倒)"],
    normalRef: "阴性(睁闭眼均稳)",
    abnormalMeaning: "阳性提示深感觉障碍(脊髓后索);睁眼即不稳→小脑病变",
  },
  {
    id: "line-drawing",
    category: "小脑与平衡",
    name: "划线试验",
    dataType: "select",
    side: "both",
    options: ["正常", "震颤", "偏斜"],
    normalRef: "直线准确",
    abnormalMeaning: "震颤/偏斜→小脑或基底节病变",
  },
  {
    id: "mmt",
    category: "肌力",
    name: "徒手肌力测试(MMT)",
    dataType: "grade-0-5",
    side: "both",
    normalRef: "5",
    abnormalMeaning: "≤3 不能抗重力,神经根/周围神经/肌肉病变",
  },

  /* ============ 步态(按步态周期时相组织) ============ */
  {
    id: "gait-ic-knee-flexion",
    category: "步态",
    name: "初次着地期-膝屈曲(loading response)",
    dataType: "select",
    side: "both",
    options: ["正常 15-20°", "减弱 (<10°)", "过伸(膝反屈)", "屈曲受限"],
    normalRef: "15-20°(吸收冲击)",
    abnormalMeaning: "减弱→股四头肌无力/制动恐惧;过伸→膝反屈;屈曲受限→膝关节病变",
  },
  {
    id: "gait-ms-hip-extension",
    category: "步态",
    name: "站立中期-髋伸展(mid-stance)",
    dataType: "select",
    side: "both",
    options: ["正常 10-15°", "减弱 (<5°)", "过度伸展"],
    normalRef: "10-15°(髋过伸位)",
    abnormalMeaning: "减弱→臀大肌无力;过度伸展→代偿髋外侧稳定肌",
  },
  {
    id: "gait-sw-hip-flexion",
    category: "步态",
    name: "摆动相-髋屈曲(swing)",
    dataType: "select",
    side: "both",
    options: ["正常 20-30°", "减弱 (<15°)", "增加 (>35°)"],
    normalRef: "20-30°",
    abnormalMeaning: "减弱→髂腰肌无力;增加→代偿性提髋步态(足下垂)",
  },
  {
    id: "gait-sw-ankle-dorsiflexion",
    category: "步态",
    name: "摆动相-踝背屈(廓清)",
    dataType: "select",
    side: "both",
    options: ["正常 0-10°", "减弱(拖足)", "增加(过度背屈)"],
    normalRef: "0-10°(足廓清)",
    abnormalMeaning: "减弱→胫前肌无力/小腿三头肌痉挛;代偿性跨阈步态",
  },
  {
    id: "gait-ts-knee-extension",
    category: "步态",
    name: "摆动末期-膝伸直(terminal swing)",
    dataType: "select",
    side: "both",
    options: ["正常 0°(完全伸直)", "屈曲残留 (>10°)", "过伸 (>5°)"],
    normalRef: "0°(完全伸直准备着地)",
    abnormalMeaning: "屈曲残留→股直肌/腘绳肌痉挛或伸膝滞后;过伸→股四头肌无力",
  },
  {
    id: "gait-sw-shoulder-rotation",
    category: "步态",
    name: "摆动相-肩带反向旋转",
    dataType: "select",
    side: "both",
    options: ["对称(反向旋转)", "减弱", "同向(异常)"],
    normalRef: "肩带与骨盆反向旋转(左肩前→右髋前)",
    abnormalMeaning: "减弱→对侧脑功能下降;同向→全身协同障碍(ANRM 经典观察)",
  },
  {
    id: "10m-walk",
    category: "步态",
    name: "10米步行测试",
    dataType: "seconds",
    side: "single",
    unit: "s",
    normalRef: "6-7s(1.4-1.7m/s)",
    abnormalMeaning: ">10s 步行能力显著下降",
  },
  {
    id: "6min-walk",
    category: "步态",
    name: "6分钟步行测试",
    dataType: "number",
    side: "single",
    unit: "m",
    normalRef: "500-700m;400-500轻;300-400中;<300重",
  },

  /* ============ 平衡 / 协调 ============ */
  {
    id: "ctsib",
    category: "小脑与平衡",
    name: "CTSIB 平衡评估(4阶段)",
    dataType: "seconds",
    side: "single",
    unit: "s",
    subItems: [
      "① 硬地睁眼(本体70/视20/前庭10)",
      "② 硬地闭眼",
      "③ 软垫睁眼",
      "④ 软垫闭眼",
    ],
    normalRef: "每阶段>15s,无晃动",
    abnormalMeaning: "① 异常→视觉依赖;② 异常→本体感觉缺失;③ 异常→前庭/本体代偿不足;④ 异常→前庭功能障碍",
  },
  {
    id: "single-leg-stand",
    category: "小脑与平衡",
    name: "单脚站立测试",
    dataType: "seconds",
    side: "both",
    unit: "s",
    normalRef: ">30s良;10-30中;<10s差",
    abnormalMeaning: "睁/闭眼差距大→本体感觉依赖",
  },
  /* ============ 自律神经 ============ */
  {
    id: "heart-rate",
    category: "自律神经",
    name: "心率(静息)",
    dataType: "number",
    side: "single",
    unit: "bpm",
    normalRef: "60-100 bpm",
    abnormalMeaning: "<60 心动过缓(迷走张力增高/药物);>100 心动过速(交感兴奋/脱水/贫血)",
  },
  {
    id: "bp-bilateral",
    category: "自律神经",
    name: "血压双侧对比",
    dataType: "select",
    side: "single",
    options: ["对称 (<10mmHg)", "左高 (10-20mmHg)", "右高 (10-20mmHg)", "差异显著 (>20mmHg)"],
    normalRef: "双臂收缩压差 <10mmHg",
    abnormalMeaning: "差异>10mmHg 提示锁骨下动脉狭窄/主动脉夹层/大动脉炎;>20mmHg 临床显著",
  },
  {
    id: "resp-rate",
    category: "自律神经",
    name: "呼吸频率",
    dataType: "number",
    side: "single",
    unit: "次/分",
    normalRef: "12-20 次/分,节律均匀",
    abnormalMeaning: "<12 呼吸过缓(中枢抑制/颅高压);>20 呼吸过速(缺氧/酸中毒/焦虑);潮式/叹息样→脑干功能障碍",
  },
  {
    id: "finger-press",
    category: "自律神经",
    name: "指压试验(末梢循环)",
    dataType: "number",
    side: "both",
    unit: "s",
    normalRef: "1-2s 再充盈",
    abnormalMeaning: ">3s 末梢循环不良(血管痉挛/低灌注/交感张力异常)",
  },
  {
    id: "baroreflex",
    category: "自律神经",
    name: "压力感受性反射",
    dataType: "select",
    side: "single",
    options: ["正常", "减弱", "消失"],
    normalRef: "血压高时心率减慢",
    abnormalMeaning: "减弱/消失→脊髓损伤辅助诊断(ANRM)",
  },
  {
    id: "cold-pressor",
    category: "自律神经",
    name: "冷加压试验",
    dataType: "select",
    side: "single",
    options: ["正常", "异常升高", "无反应"],
    normalRef: "血压略升后恢复",
    abnormalMeaning: "异常升高→交感神经过度兴奋;无反应→自主神经衰竭",
  },
  {
    id: "pupil-flutter",
    category: "自律神经",
    name: "瞳孔波动幅度/频率",
    dataType: "select",
    side: "both",
    options: ["正常", "减弱", "增强"],
    normalRef: "稳定小幅波动",
    abnormalMeaning: "增强→交感神经兴奋;眼底AV比1:1→1:2",
  },

  /* ============ 量表评估(自动计分) ============ */
  {
    id: "scale-berg",
    category: "量表",
    name: "Berg 平衡量表",
    dataType: "number",
    side: "single",
    unit: "分",
    normalRef: "56分满分;41-55低风险;21-40中风险;0-20高风险",
  },
  {
    id: "scale-tinetti",
    category: "量表",
    name: "Tinetti 步态量表",
    dataType: "number",
    side: "single",
    unit: "分",
    normalRef: "满分16;12-16良;8-11轻;4-7中;0-3重",
  },
  {
    id: "scale-fugl-meyer",
    category: "量表",
    name: "Fugl-Meyer 运动功能评分",
    dataType: "number",
    side: "single",
    unit: "分",
    normalRef: "上肢66分+下肢34分=100分",
  },
  {
    id: "scale-barthel",
    category: "量表",
    name: "Barthel 指数(ADL)",
    dataType: "number",
    side: "single",
    unit: "分",
    normalRef: "100分独立;60-99轻度依赖;40-59中度;<40重度",
  },
  {
    id: "scale-mmse",
    category: "量表",
    name: "MMSE 简易精神状态",
    dataType: "number",
    side: "single",
    unit: "分",
    normalRef: "≥27正常;21-26轻度;10-20中度;<10重度",
  },
  {
    id: "scale-vas",
    category: "量表",
    name: "疼痛 VAS",
    dataType: "number",
    side: "single",
    unit: "分",
    normalRef: "0无痛,10最剧烈",
  },
  /* ============ 疼痛评估量表(患者自评) ============ */
  {
    id: "scale-csi",
    category: "量表",
    name: "CSI 中枢敏感性量表(患者自评·25项)",
    dataType: "number",
    side: "none",
    unit: "分",
    normalRef: "每项0-4;总分0-100;≥40提示中枢敏化",
    subItems: [
      "1.睡醒时疲倦没精神",
      "2.肌肉僵硬酸痛",
      "3.焦虑发作",
      "4.磨牙或咬紧牙关",
      "5.腹泻/便秘",
      "6.日常生活需帮助",
      "7.对强光敏感",
      "8.易疲劳(体力活动)",
      "9.全身疼痛",
      "10.头痛",
      "11.膀胱不适/小便灼烧",
      "12.睡眠不佳",
      "13.注意力不集中",
      "14.皮肤干燥/瘙痒/皮疹",
      "15.压力加重症状",
      "16.悲伤或抑郁",
      "17.精力不足",
      "18.颈肩部肌肉紧张",
      "19.下巴疼痛",
      "20.气味敏感(香水等)",
      "21.尿频",
      "22.腿部不适(入睡时)",
      "23.记忆力差",
      "24.童年创伤",
      "25.盆腔疼痛",
    ] as const,
  },
  {
    id: "scale-slanss",
    category: "量表",
    name: "S-LANSS 神经病理性疼痛自评(患者自评·7项)",
    dataType: "number",
    side: "none",
    unit: "分",
    normalRef: "总分0-24;≥12提示神经病理性疼痛",
    subItems: [
      "1.针刺感/发麻感",
      "2.肤色改变(斑驳/发红)",
      "3.轻触异常敏感",
      "4.突然爆发(电击/跳痛)",
      "5.灼热痛",
      "6.摩擦痛(与非痛区对比)",
      "7.按压痛(与非痛区对比)",
    ] as const,
  },
];
