/**
 * ANRM 特色临床神经科学查体目录。
 * 从 ANRM 肌骨神经康复系列手册提取,正常值/分级待医师签字确认。
 */
import type { ExamItemDef } from "./exam.types";

export const EXAM_CATALOG: readonly ExamItemDef[] = [
  /* ============ 原始反射 ============ */
  {
    id: "moro",
    category: "原始反射",
    name: "惊吓反射(Moro)",
    dataType: "pos-neg",
    side: "single",
    normalRef: "阴性(3月后应消失)",
    abnormalMeaning: "阳性提示中脑/脑干未整合,常见于 ADHD、焦虑、姿势控制障碍",
    pendingConfirmation: true,
  },
  {
    id: "spinal-galant",
    category: "原始反射",
    name: "脊髓背反射(Galant)",
    dataType: "pos-neg",
    side: "both",
    normalRef: "阴性(9月后应消失)",
    abnormalMeaning: "阳性提示 T12-L1 水平神经兴奋性增高,与排尿控制相关",
    pendingConfirmation: true,
  },
  {
    id: "tlr",
    category: "原始反射",
    name: "迷路反射(TLR)",
    dataType: "select",
    side: "single",
    options: ["阴性", "轻度阳性", "中度阳性", "重度阳性"],
    normalRef: "阴性(3岁后)",
    abnormalMeaning: "抬头/点头时躯干晃动,前庭系统未成熟",
    pendingConfirmation: true,
  },
  {
    id: "atnr",
    category: "原始反射",
    name: "不对称性颈反射(ATNR)",
    dataType: "select",
    side: "both",
    options: ["阴性", "弱阳性", "强阳性"],
    normalRef: "阴性(6月后应消失)",
    abnormalMeaning: "残留影响惯用手发育、读写能力、左右分化",
    pendingConfirmation: true,
  },
  {
    id: "stnr",
    category: "原始反射",
    name: "对称性颈反射(STNR)",
    dataType: "pos-neg",
    side: "single",
    normalRef: "阴性(11月后应消失)",
    abnormalMeaning: "残留影响爬行、坐姿、专注力",
    pendingConfirmation: true,
  },

  /* ============ 脑神经 ============ */
  {
    id: "babinski",
    category: "脑神经",
    name: "巴宾斯基征(Babinski)",
    dataType: "select",
    side: "both",
    options: ["阴性", "弱阳性", "强阳性"],
    normalRef: "阴性(成人)",
    abnormalMeaning: "阳性提示锥体束损伤;左阳→右脑,右阳→左脑",
    pendingConfirmation: true,
  },
  {
    id: "hoffmann",
    category: "脑神经",
    name: "霍夫曼征(Hoffmann)",
    dataType: "pos-neg",
    side: "both",
    normalRef: "阴性",
    abnormalMeaning: "阳性提示上运动神经元病变",
    pendingConfirmation: true,
  },
  {
    id: "pupillary-reflex",
    category: "脑神经",
    name: "瞳孔对光反射",
    dataType: "select",
    side: "both",
    options: ["灵敏", "迟钝", "消失"],
    normalRef: "灵敏(幅度/速度/频率正常)",
    abnormalMeaning: "迟钝/消失提示动眼神经(III)或中脑病变",
    pendingConfirmation: true,
  },
  {
    id: "eyeball-movement",
    category: "脑神经",
    name: "眼球运动(III-IV-VI)",
    dataType: "select",
    side: "both",
    options: ["正常", "受限", "复视"],
    normalRef: "各方向活动自如",
    abnormalMeaning: "受限提示第3/4/6脑神经或脑干病变",
    pendingConfirmation: true,
  },

  /* ============ 前庭-眼动(ANRM 特色) ============ */
  {
    id: "vor-head-impulse",
    category: "前庭-眼动",
    name: "甩头试验(Head Impulse)",
    dataType: "pos-neg",
    side: "both",
    normalRef: "阴性(眼动可代偿)",
    abnormalMeaning: "阳性提示前庭眼反射(VOR)通路异常",
    pendingConfirmation: true,
  },
  {
    id: "vor-gain",
    category: "前庭-眼动",
    name: "VOR 增益",
    dataType: "number",
    side: "both",
    unit: "倍",
    normalRef: "≈1.0",
    abnormalMeaning: "<0.8 前庭功能减退;>1.2 小脑代偿过度",
    pendingConfirmation: true,
  },
  {
    id: "saccade",
    category: "前庭-眼动",
    name: "扫视(Saccade)-第8区",
    dataType: "select",
    side: "single",
    options: ["正常", "启动延迟", "欠冲", "过冲"],
    normalRef: "快速准确,启动<200ms",
    abnormalMeaning: "延迟提示额叶/第8区问题",
    pendingConfirmation: true,
  },
  {
    id: "smooth-pursuit",
    category: "前庭-眼动",
    name: "平滑追踪(Smooth Pursuit)",
    dataType: "select",
    side: "both",
    options: ["正常", "扫视性追踪", "显著受限"],
    normalRef: "眼球可平滑追踪移动目标",
    abnormalMeaning: "扫视性追踪提示脑干/小脑/顶叶病变",
    pendingConfirmation: true,
  },
  {
    id: "vergence",
    category: "前庭-眼动",
    name: "视轴聚散度(Convergence)",
    dataType: "number",
    side: "single",
    unit: "cm",
    normalRef: "成人10-15cm,儿童6-8cm",
    abnormalMeaning: ">15cm 聚散不足,中脑/动眼神经核问题",
    pendingConfirmation: true,
  },
  {
    id: "neck-proprioception",
    category: "前庭-眼动",
    name: "颈椎本体位置觉",
    dataType: "number",
    side: "single",
    unit: "°",
    normalRef: "闭眼转20°,误差<3°",
    abnormalMeaning: "颈椎本体感觉减退,颈性眩晕风险",
    pendingConfirmation: true,
  },

  /* ============ 反射 / 肌张力 ============ */
  {
    id: "deep-reflex-biceps",
    category: "反射",
    name: "肱二头肌反射",
    dataType: "grade-0-4",
    side: "both",
    normalRef: "2+",
    abnormalMeaning: "0-1+ 下运动神经元;3-4+ 上运动神经元",
  },
  {
    id: "deep-reflex-triceps",
    category: "反射",
    name: "肱三头肌反射",
    dataType: "grade-0-4",
    side: "both",
    normalRef: "2+",
  },
  {
    id: "deep-reflex-brachioradialis",
    category: "反射",
    name: "桡骨膜反射",
    dataType: "grade-0-4",
    side: "both",
    normalRef: "2+",
  },
  {
    id: "deep-reflex-patellar",
    category: "反射",
    name: "膝腱反射",
    dataType: "grade-0-4",
    side: "both",
    normalRef: "2+",
  },
  {
    id: "deep-reflex-achilles",
    category: "反射",
    name: "跟腱反射",
    dataType: "grade-0-4",
    side: "both",
    normalRef: "2+",
    abnormalMeaning: "消失提示S1-S2神经根病变",
  },
  {
    id: "mas",
    category: "反射",
    name: "改良 Ashworth 痉挛量表(MAS)",
    dataType: "select",
    side: "both",
    options: ["0", "1", "1+", "2", "3", "4"],
    normalRef: "0",
    abnormalMeaning: "≥1 痉挛,分级越高痉挛越重",
  },
  {
    id: "clonus",
    category: "反射",
    name: "踝阵挛",
    dataType: "pos-neg",
    side: "both",
    normalRef: "阴性",
    abnormalMeaning: "阳性提示上运动神经元病变",
  },

  /* ============ 感觉 / 本体感觉 ============ */
  {
    id: "tactile",
    category: "感觉",
    name: "浅感觉(触觉)",
    dataType: "select",
    side: "both",
    options: ["正常", "减退", "消失", "过敏"],
    normalRef: "正常",
  },
  {
    id: "pain-sense",
    category: "感觉",
    name: "痛觉",
    dataType: "select",
    side: "both",
    options: ["正常", "减退", "消失", "过敏"],
    normalRef: "正常",
  },
  {
    id: "temperature-sense",
    category: "感觉",
    name: "温度觉",
    dataType: "select",
    side: "both",
    options: ["正常", "减退", "消失"],
    normalRef: "正常",
  },
  {
    id: "vibration-sense",
    category: "感觉",
    name: "震动觉",
    dataType: "select",
    side: "both",
    options: ["正常", "减退", "消失"],
    normalRef: "正常",
    abnormalMeaning: "减退提示脊髓后索病变",
  },
  {
    id: "joint-position",
    category: "感觉",
    name: "关节位置觉",
    dataType: "select",
    side: "both",
    options: ["正常", "减退", "消失"],
    normalRef: "正常",
    abnormalMeaning: "减退提示脊髓后索/薄束楔束病变,比疼痛觉更重要(ANRM)",
  },
  {
    id: "two-point",
    category: "感觉",
    name: "两点辨识觉",
    dataType: "number",
    side: "both",
    unit: "mm",
    normalRef: "指尖2-4mm,手掌8-10mm,背部40-70mm",
    abnormalMeaning: "增大提示感觉通路/皮层感觉区病变",
    pendingConfirmation: true,
  },
  {
    id: "finger-press",
    category: "感觉",
    name: "指压试验(末梢循环)",
    dataType: "number",
    side: "both",
    unit: "s",
    normalRef: "1-2s",
    abnormalMeaning: ">3s 末梢循环不良",
    pendingConfirmation: true,
  },

  /* ============ 运动控制(ANRM 特色) ============ */
  {
    id: "finger-nose",
    category: "运动控制",
    name: "指鼻试验",
    dataType: "select",
    side: "both",
    options: ["正常", "轻度不稳", "明显不稳", "无法完成"],
    normalRef: "正常",
    abnormalMeaning: "意向性震颤→小脑病变",
  },
  {
    id: "heel-shin",
    category: "运动控制",
    name: "跟膝胫试验",
    dataType: "select",
    side: "both",
    options: ["正常", "轻度不稳", "明显不稳", "无法完成"],
    normalRef: "正常",
  },
  {
    id: "diadochokinesia",
    category: "运动控制",
    name: "轮替动作",
    dataType: "select",
    side: "both",
    options: ["正常", "笨拙", "不能完成"],
    normalRef: "正常",
    abnormalMeaning: "轮替运动障碍→小脑半球病变",
  },
  {
    id: "apa",
    category: "运动控制",
    name: "预期姿势调整(APA)",
    dataType: "select",
    side: "single",
    options: ["正常", "延迟", "缺失"],
    normalRef: "正常",
    abnormalMeaning: "延迟/缺失提示基底节或额叶运动计划区问题",
    pendingConfirmation: true,
  },
  {
    id: "mmt",
    category: "肌力",
    name: "徒手肌力测试(MMT)",
    dataType: "grade-0-5",
    side: "both",
    normalRef: "5",
    abnormalMeaning: "≤3 不能抗重力,神经根/周围神经/肌肉病变",
  },

  /* ============ 步态(ANRM 四指标) ============ */
  {
    id: "gait-shoulder",
    category: "步态",
    name: "步态-肩膀甩动",
    dataType: "select",
    side: "both",
    options: ["正常", "减少", "增加"],
    normalRef: "对称摆动",
    abnormalMeaning: "减少→对侧脑功能下降(ANRM)",
    pendingConfirmation: true,
  },
  {
    id: "gait-elbow",
    category: "步态",
    name: "步态-手肘摆动",
    dataType: "select",
    side: "both",
    options: ["正常", "减少", "增加"],
    normalRef: "对称摆动",
    abnormalMeaning: "减少→同侧小脑功能下降(ANRM)",
    pendingConfirmation: true,
  },
  {
    id: "gait-angle",
    category: "步态",
    name: "步态-宽深角度",
    dataType: "select",
    side: "both",
    options: ["正常", "异常"],
    normalRef: "足偏角5-10°外旋",
    abnormalMeaning: "异常→同侧脑功能下降(ANRM)",
    pendingConfirmation: true,
  },
  {
    id: "gait-knee-brake",
    category: "步态",
    name: "步态-膝关节刹车",
    dataType: "select",
    side: "both",
    options: ["正常", "减弱", "消失"],
    normalRef: "正常减速控制",
    abnormalMeaning: "减弱→对侧脑/小脑功能下降(ANRM)",
    pendingConfirmation: true,
  },
  {
    id: "10m-walk",
    category: "步态",
    name: "10米步行测试",
    dataType: "seconds",
    side: "single",
    unit: "s",
    normalRef: "6-7s(1.4-1.7m/s)",
    abnormalMeaning: ">10s 步行能力显著下降",
    pendingConfirmation: true,
  },
  {
    id: "6min-walk",
    category: "步态",
    name: "6分钟步行测试",
    dataType: "number",
    side: "single",
    unit: "m",
    normalRef: "500-700m;400-500轻;300-400中;<300重",
    pendingConfirmation: true,
  },

  /* ============ 平衡 / 协调 ============ */
  {
    id: "ctsib",
    category: "平衡协调",
    name: "CTSIB 平衡评估(4阶段)",
    dataType: "text",
    side: "single",
    normalRef: "每阶段保持>15s,无显著晃动",
    abnormalMeaning: "①硬地睁眼(本体70/视20/前庭10);②硬地闭眼;③软垫睁眼;④软垫闭眼",
    pendingConfirmation: true,
  },
  {
    id: "single-leg-stand",
    category: "平衡协调",
    name: "单脚站立测试",
    dataType: "seconds",
    side: "both",
    unit: "s",
    normalRef: ">30s良;10-30中;<10s差",
    abnormalMeaning: "睁/闭眼差距大→本体感觉依赖",
    pendingConfirmation: true,
  },
  {
    id: "frt",
    category: "平衡协调",
    name: "功能性伸展测试(FRT)",
    dataType: "number",
    side: "single",
    unit: "cm",
    normalRef: ">25cm",
    abnormalMeaning: "<15cm 跌倒风险高",
    pendingConfirmation: true,
  },
  {
    id: "thomas-test",
    category: "平衡协调",
    name: "托马斯测试(Thomas Test)",
    dataType: "number",
    side: "both",
    unit: "°",
    normalRef: ">20°",
    abnormalMeaning: "髋屈曲挛缩",
    pendingConfirmation: true,
  },
  {
    id: "tug",
    category: "平衡协调",
    name: "起立-行走计时(TUG)",
    dataType: "seconds",
    side: "single",
    unit: "s",
    normalRef: "≤10s正;10-20轻;20-30中;>30重",
    abnormalMeaning: ">13.5s 跌倒风险增加",
    pendingConfirmation: true,
  },

  /* ============ 自律神经 ============ */
  {
    id: "baroreflex",
    category: "自律神经",
    name: "压力感受性反射",
    dataType: "select",
    side: "single",
    options: ["正常", "减弱", "消失"],
    normalRef: "血压高时心率减慢",
    abnormalMeaning: "减弱/消失→脊髓损伤辅助诊断(ANRM)",
    pendingConfirmation: true,
  },
  {
    id: "cold-pressor",
    category: "自律神经",
    name: "冷加压试验",
    dataType: "select",
    side: "single",
    options: ["正常", "异常升高", "无反应"],
    normalRef: "血压略升后恢复",
    abnormalMeaning: "异常升高→交感神经过度兴奋;无反应→自主神经衰竭",
    pendingConfirmation: true,
  },
  {
    id: "pupil-flutter",
    category: "自律神经",
    name: "瞳孔波动幅度/频率",
    dataType: "select",
    side: "both",
    options: ["正常", "减弱", "增强"],
    normalRef: "稳定小幅波动",
    abnormalMeaning: "增强→交感神经兴奋;眼底AV比1:1→1:2",
    pendingConfirmation: true,
  },

  /* ============ 量表评估(自动计分) ============ */
  {
    id: "scale-berg",
    category: "量表",
    name: "Berg 平衡量表",
    dataType: "number",
    side: "single",
    unit: "分",
    normalRef: "56分满分;41-55低风险;21-40中风险;0-20高风险",
    pendingConfirmation: true,
  },
  {
    id: "scale-tinetti",
    category: "量表",
    name: "Tinetti 步态量表",
    dataType: "number",
    side: "single",
    unit: "分",
    normalRef: "满分16;12-16良;8-11轻;4-7中;0-3重",
    pendingConfirmation: true,
  },
  {
    id: "scale-fugl-meyer",
    category: "量表",
    name: "Fugl-Meyer 运动功能评分",
    dataType: "number",
    side: "single",
    unit: "分",
    normalRef: "上肢66分+下肢34分=100分",
    pendingConfirmation: true,
  },
  {
    id: "scale-barthel",
    category: "量表",
    name: "Barthel 指数(ADL)",
    dataType: "number",
    side: "single",
    unit: "分",
    normalRef: "100分独立;60-99轻度依赖;40-59中度;<40重度",
    pendingConfirmation: true,
  },
  {
    id: "scale-mmse",
    category: "量表",
    name: "MMSE 简易精神状态",
    dataType: "number",
    side: "single",
    unit: "分",
    normalRef: "≥27正常;21-26轻度;10-20中度;<10重度",
    pendingConfirmation: true,
  },
  {
    id: "scale-vas",
    category: "量表",
    name: "疼痛 VAS",
    dataType: "number",
    side: "single",
    unit: "分",
    normalRef: "0无痛,10最剧烈",
  },
];
